apiVersion: v1
kind: Template
metadata:
  name: amun-role
  annotations:
    description: This is Amun Role template
    openshift.io/display-name: "Amun Role"
    version: 0.5.1
    tags: amun,thoth,ai-stacks,aistacks,machinelearning
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Amun to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.5.1
  labels:
    template: amun-role
    app: amun

objects:
  - apiVersion: authorization.openshift.io/v1
    kind: Role
    metadata:
      name: amun
      annotations:
        thoth-station.ninja/template-version: 0.5.1
      labels:
        app: amun
    rules:
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - pods
          - pods/attach
          - pods/exec
        verbs:
          - create
          - get
          - list
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - configmaps
        verbs:
          - create
          - get
          - list
      - apiGroups:
          - ""
        attributeRestrictions: null
        resources:
          - pods/log
          - pods/status
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - batch
        attributeRestrictions: null
        resources:
          - cronjobs
          - jobs
        verbs:
          - create
          - get
          - list
          - watch
      - apiGroups:
          - ""
          - build.openshift.io
        attributeRestrictions: null
        resources:
          - buildconfigs
          - buildconfigs/webhooks
          - builds
        verbs:
          - create
          - get
          - list
          - watch
      - apiGroups:
          - ""
          - build.openshift.io
        attributeRestrictions: null
        resources:
          - builds/log
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ""
          - build.openshift.io
        attributeRestrictions: null
        resources:
          - buildconfigs/instantiate
          - buildconfigs/instantiatebinary
          - builds/clone
        verbs:
          - create
      - apiGroups:
          - ""
          - image.openshift.io
        attributeRestrictions: null
        resources:
          - imagestreamimages
          - imagestreammappings
          - imagestreams
          - imagestreams/secrets
          - imagestreamtags
        verbs:
          - create
          - get
          - list
          - watch
      - apiGroups:
          - ""
          - image.openshift.io
        attributeRestrictions: null
        resources:
          - imagestreams/status
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - ""
          - image.openshift.io
        attributeRestrictions: null
        resources:
          - imagestreams/layers
        verbs:
          - get
          - update
      - apiGroups:
          - ""
          - template.openshift.io
        attributeRestrictions: null
        resources:
          - processedtemplates
          - templateconfigs
          - templateinstances
          - templates
        verbs:
          - create
          - get
          - list
          - watch
      - apiGroups:
          - ""
          - build.openshift.io
        attributeRestrictions: null
        resources:
          - buildlogs
        verbs:
          - create
          - get
          - list
          - watch
      - apiGroups:
          - argoproj.io
        resources:
          - workflows
          - workflows/finalizers
        verbs:
          - create
          - get
          - list
      - apiGroups:
          - argoproj.io
        resources:
          - workflowtemplates
          - workflowtemplates/finalizers
        verbs:
          - create
          - get
          - list
