apiVersion: v1
kind: Template
metadata:
  name: amun-api-imagestream
  annotations:
    description: This is Amun API Imagestream.
    openshift.io/display-name: "Amun API: ImageStream"
    version: 0.5.1
    tags: amun,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This is Amun API ImageStream.
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.5.1
  labels:
    template: amun-api-imagestream
    app: amun
    component: amun-api
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      annotations:
        thoth-station.ninja/template-version: 0.5.1
      labels:
        app: amun
        component: amun-api
      name: amun-api
    spec:
      name: latest
      lookupPolicy:
        local: true
